import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";
import { SearchInput } from "@/ui/atoms/SearchInput";
import { ShoppingCart } from "lucide-react";
import Link from "next/link";
import { getCartFromCookies } from "./api/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const cart = await getCartFromCookies();
	const quantity = cart?.orderItems.length ?? 0;

	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex items-center justify-between p-4">
					<div className="text-2xl font-bold">Next.js masters</div>
					<div className="flex flex-row">
						<SearchInput />
						<ul className="flex">
							<li className="mx-4">
								<ActiveLink
									href="/"
									className="hover:text-blue border-black text-white"
									activeClassName="underline border-black"
								>
									Home
								</ActiveLink>
							</li>
							<li className="mx-4">
								<ActiveLink
									href="/products"
									className="hover:text-blue border-black text-white"
									activeClassName="underline border-white"
									exact={true}
								>
									All
								</ActiveLink>
							</li>
							<li className="mx-4">
								<ActiveLink
									href="/products/categories"
									className="hover:text-blue border-black text-white"
									activeClassName="underline border-white"
									exact={false}
								>
									Categories
								</ActiveLink>
							</li>
							<li>
								<Link
									href="/cart"
									className="group -m-2 flex items-center p-2"
								>
									<ShoppingCart
										className="h-6 w-6 flex-shrink-0"
										aria-hidden="true"
									/>
									<span className="ml-2 text-sm font-medium">
										{quantity}
									</span>
								</Link>
							</li>
						</ul>
					</div>
				</nav>
				<section className="sm:py-15 md:max-2-4xl mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 lg:max-w-7xl">
					{children}
				</section>
				<footer>
					<p className="text-center text-sm text-gray-500">2023</p>
				</footer>
			</body>
		</html>
	);
}
